# SPDX-FileCopyrightText: 2026 The Matrix.org Foundation C.I.C.
#
# SPDX-License-Identifier: Apache-2.0

# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - dependencies

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - dependencies
    groups:
      npm:
        patterns: ["*"]
